config/routes.rb
Rails.application.routes.draw do
  
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true
	validates :age, presence: true
	validates :cuteness, presence: true
	validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.json { render :json => @kittens }
		end
	end

	def show
		@kitten = Kitten.find(params[:id])
		respond_to do |format|
			format.html
			format.json { render :json => @kitten }
		end
	end

	def new
		@kitten = Kitten.create
	end

	def create
		@kitten = Kitten.create(kitten_params)
		if @kitten.save
			flash[:success] = "Kitten successfully registered!"
			redirect_to @kitten
		else
			flash.now[:error] = "Are you sure you have a kitten? If so, enter all the info."
			render :new
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten successfully updated!"
			redirect_to @kitten
		else
			flash.now[:error] = "Are you sure you know this kitten? If so, enter all the info."
			render :edit
		end
	end

	def destroy
		Kitten.find(params[:id]).destroy
		flash[:success] = "Kitten successfully deleted!"
		redirect_to root_url
	end

	private

	def kitten_params
		params.require(:kitten).permit(:name, :age, :cuteness, :softness)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
	<%= f.label :name, "Name: " %>
	<%= f.text_field :name %>

	<%= f.label :age, "Age :" %>
	<%= f.number_field :age %>

	<%= f.label :cuteness, "Cuteness: " %>
	<%= f.number_field :cuteness %>

	<%= f.label :softness, "Softness: " %>
	<%= f.number_field :softness %>

	<%= f.submit "Submit" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Your Kittens Info</h1>
<%= render "form" %>

app/views/kittens/index.html.erb
<% if @kittens.empty? %>
	<h1>There are no kittens registered yet</h1>
<% else %>
	<h1>Kittens</h1>
	<ol>
		<% @kittens.each do |kitten| %>
			<li><%= link_to kitten.name, kitten_path(kitten) %></li>
				<ul>
					<li>Age: <%= kitten.age %></li>
					<li>Cuteness: <%= kitten.cuteness %></li>
					<li>Softness: <%= kitten.softness %></li>
				</ul>
			<%= link_to "Edit", edit_kitten_path(kitten) %> <%= link_to "Delete", kitten_path(kitten), method: :delete %>
		<% end %>
	</ol>
<% end %>
<%= link_to "Register a kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Register a Kitten</h1>
<%= render "form" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<ul>
	<li>Age: <%= @kitten.age %></li>
	<li>Cuteness: <%= @kitten.cuteness %></li>
	<li>Softness: <%= @kitten.softness %></li>
</ul>

<%= link_to "Edit", edit_kitten_path %>
<%= link_to "Delete", kitten_path(@kitten), method: :delete %>
<%= link_to "All Kittens", kittens_path %>

app/views/layouts/_alert.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= key %>">
        <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% unless flash.empty? %>
  		<%= render "layouts/alert" %>
  	<% end %>
  	
    <%= yield %>
  </body>
</html>